# 
# Report generation script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
proc start_step { step } {
  set stopFile ".stop.rst"
  if {[file isfile .stop.rst]} {
    puts ""
    puts "*** Halting run - EA reset detected ***"
    puts ""
    puts ""
    return -code error
  }
  set beginFile ".$step.begin.rst"
  set platform "$::tcl_platform(platform)"
  set user "$::tcl_platform(user)"
  set pid [pid]
  set host ""
  if { [string equal $platform unix] } {
    if { [info exist ::env(HOSTNAME)] } {
      set host $::env(HOSTNAME)
    }
  } else {
    if { [info exist ::env(COMPUTERNAME)] } {
      set host $::env(COMPUTERNAME)
    }
  }
  set ch [open $beginFile w]
  puts $ch "<?xml version=\"1.0\"?>"
  puts $ch "<ProcessHandle Version=\"1\" Minor=\"0\">"
  puts $ch "    <Process Command=\".planAhead.\" Owner=\"$user\" Host=\"$host\" Pid=\"$pid\">"
  puts $ch "    </Process>"
  puts $ch "</ProcessHandle>"
  close $ch
}

proc end_step { step } {
  set endFile ".$step.end.rst"
  set ch [open $endFile w]
  close $ch
}

proc step_failed { step } {
  set endFile ".$step.error.rst"
  set ch [open $endFile w]
  close $ch
}


start_step init_design
set ACTIVE_STEP init_design
set rc [catch {
  create_msg_db init_design.pb
  create_project -in_memory -part xc7z020clg484-1
  set_property board_part numato.com:styx:part0:1.0 [current_project]
  set_property design_mode GateLvl [current_fileset]
  set_param project.singleFileAddWarning.threshold 0
  set_property webtalk.parent_dir /home/mike/agc_monitor/fpga/agc_monitor.cache/wt [current_project]
  set_property parent.project_path /home/mike/agc_monitor/fpga/agc_monitor.xpr [current_project]
  set_property ip_output_repo /home/mike/agc_monitor/fpga/agc_monitor.cache/ip [current_project]
  set_property ip_cache_permissions {read write} [current_project]
  set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
  add_files -quiet /home/mike/agc_monitor/fpga/agc_monitor.runs/synth_1/agc_monitor.dcp
  set_msg_config -source 4 -id {BD 41-1661} -limit 0
  set_param project.isImplRun true
  add_files /home/mike/agc_monitor/fpga/agc_monitor.srcs/sources_1/bd/monitor_ps/monitor_ps.bd
  read_ip -quiet /home/mike/agc_monitor/fpga/agc_monitor.srcs/sources_1/ip/cmd_fifo/cmd_fifo.xci
  read_ip -quiet /home/mike/agc_monitor/fpga/agc_monitor.srcs/sources_1/ip/read_fifo/read_fifo.xci
  read_ip -quiet /home/mike/agc_monitor/fpga/agc_monitor.srcs/sources_1/ip/read_byte_fifo/read_byte_fifo.xci
  read_ip -quiet /home/mike/agc_monitor/fpga/agc_monitor.srcs/sources_1/ip/mon_adc/mon_adc.xci
  read_ip -quiet /home/mike/agc_monitor/fpga/agc_monitor.srcs/sources_1/ip/rope_sim_mem/rope_sim_mem.xci
  read_ip -quiet /home/mike/agc_monitor/fpga/agc_monitor.srcs/sources_1/ip/erasable_sim_mem/erasable_sim_mem.xci
  set_param project.isImplRun false
  read_xdc /home/mike/agc_monitor/fpga/agc_monitor.srcs/constrs_1/new/agc_monitor.xdc
  set_param project.isImplRun true
  link_design -top agc_monitor -part xc7z020clg484-1
  set_param project.isImplRun false
  write_hwdef -force -file agc_monitor.hwdef
  close_msg_db -file init_design.pb
} RESULT]
if {$rc} {
  step_failed init_design
  return -code error $RESULT
} else {
  end_step init_design
  unset ACTIVE_STEP 
}

start_step opt_design
set ACTIVE_STEP opt_design
set rc [catch {
  create_msg_db opt_design.pb
  opt_design 
  write_checkpoint -force agc_monitor_opt.dcp
  create_report "impl_1_opt_report_drc_0" "report_drc -file agc_monitor_drc_opted.rpt -pb agc_monitor_drc_opted.pb -rpx agc_monitor_drc_opted.rpx"
  close_msg_db -file opt_design.pb
} RESULT]
if {$rc} {
  step_failed opt_design
  return -code error $RESULT
} else {
  end_step opt_design
  unset ACTIVE_STEP 
}

start_step place_design
set ACTIVE_STEP place_design
set rc [catch {
  create_msg_db place_design.pb
  if { [llength [get_debug_cores -quiet] ] > 0 }  { 
    implement_debug_core 
  } 
  place_design 
  write_checkpoint -force agc_monitor_placed.dcp
  create_report "impl_1_place_report_io_0" "report_io -file agc_monitor_io_placed.rpt"
  create_report "impl_1_place_report_utilization_0" "report_utilization -file agc_monitor_utilization_placed.rpt -pb agc_monitor_utilization_placed.pb"
  create_report "impl_1_place_report_control_sets_0" "report_control_sets -verbose -file agc_monitor_control_sets_placed.rpt"
  close_msg_db -file place_design.pb
} RESULT]
if {$rc} {
  step_failed place_design
  return -code error $RESULT
} else {
  end_step place_design
  unset ACTIVE_STEP 
}

start_step route_design
set ACTIVE_STEP route_design
set rc [catch {
  create_msg_db route_design.pb
  route_design 
  write_checkpoint -force agc_monitor_routed.dcp
  create_report "impl_1_route_report_drc_0" "report_drc -file agc_monitor_drc_routed.rpt -pb agc_monitor_drc_routed.pb -rpx agc_monitor_drc_routed.rpx"
  create_report "impl_1_route_report_methodology_0" "report_methodology -file agc_monitor_methodology_drc_routed.rpt -pb agc_monitor_methodology_drc_routed.pb -rpx agc_monitor_methodology_drc_routed.rpx"
  create_report "impl_1_route_report_power_0" "report_power -file agc_monitor_power_routed.rpt -pb agc_monitor_power_summary_routed.pb -rpx agc_monitor_power_routed.rpx"
  create_report "impl_1_route_report_route_status_0" "report_route_status -file agc_monitor_route_status.rpt -pb agc_monitor_route_status.pb"
  create_report "impl_1_route_report_timing_summary_0" "report_timing_summary -max_paths 10 -file agc_monitor_timing_summary_routed.rpt -pb agc_monitor_timing_summary_routed.pb -rpx agc_monitor_timing_summary_routed.rpx -warn_on_violation "
  create_report "impl_1_route_report_incremental_reuse_0" "report_incremental_reuse -file agc_monitor_incremental_reuse_routed.rpt"
  create_report "impl_1_route_report_clock_utilization_0" "report_clock_utilization -file agc_monitor_clock_utilization_routed.rpt"
  create_report "impl_1_route_report_bus_skew_0" "report_bus_skew -warn_on_violation -file agc_monitor_bus_skew_routed.rpt -pb agc_monitor_bus_skew_routed.pb -rpx agc_monitor_bus_skew_routed.rpx"
  close_msg_db -file route_design.pb
} RESULT]
if {$rc} {
  write_checkpoint -force agc_monitor_routed_error.dcp
  step_failed route_design
  return -code error $RESULT
} else {
  end_step route_design
  unset ACTIVE_STEP 
}

start_step write_bitstream
set ACTIVE_STEP write_bitstream
set rc [catch {
  create_msg_db write_bitstream.pb
  set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
  catch { write_mem_info -force agc_monitor.mmi }
  write_bitstream -force agc_monitor.bit 
  catch { write_sysdef -hwdef agc_monitor.hwdef -bitfile agc_monitor.bit -meminfo agc_monitor.mmi -file agc_monitor.sysdef }
  catch {write_debug_probes -quiet -force agc_monitor}
  catch {file copy -force agc_monitor.ltx debug_nets.ltx}
  close_msg_db -file write_bitstream.pb
} RESULT]
if {$rc} {
  step_failed write_bitstream
  return -code error $RESULT
} else {
  end_step write_bitstream
  unset ACTIVE_STEP 
}

