# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/mike/agc_monitor/fpga/agc_monitor.srcs/sources_1/ip/mon_adc/mon_adc.xci
# IP: The module: 'mon_adc' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/mike/agc_monitor/fpga/agc_monitor.srcs/sources_1/ip/mon_adc/mon_adc_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mon_adc'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/mike/agc_monitor/fpga/agc_monitor.srcs/sources_1/ip/mon_adc/mon_adc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mon_adc'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/mike/agc_monitor/fpga/agc_monitor.srcs/sources_1/ip/mon_adc/mon_adc.xci
# IP: The module: 'mon_adc' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/mike/agc_monitor/fpga/agc_monitor.srcs/sources_1/ip/mon_adc/mon_adc_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mon_adc'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/mike/agc_monitor/fpga/agc_monitor.srcs/sources_1/ip/mon_adc/mon_adc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mon_adc'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
