# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/mike/agc_monitor/fpga/agc_monitor.srcs/sources_1/ip/read_fifo/read_fifo.xci
# IP: The module: 'read_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/mike/agc_monitor/fpga/agc_monitor.srcs/sources_1/ip/read_fifo/read_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'read_fifo'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/mike/agc_monitor/fpga/agc_monitor.srcs/sources_1/ip/read_fifo/read_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'read_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/mike/agc_monitor/fpga/agc_monitor.srcs/sources_1/ip/read_fifo/read_fifo.xci
# IP: The module: 'read_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/mike/agc_monitor/fpga/agc_monitor.srcs/sources_1/ip/read_fifo/read_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'read_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/mike/agc_monitor/fpga/agc_monitor.srcs/sources_1/ip/read_fifo/read_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'read_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
