# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/agc_monitor.xdc

# Block Designs: bd/monitor_ps/monitor_ps.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==monitor_ps || ORIG_REF_NAME==monitor_ps} -quiet] -quiet

# IP: bd/monitor_ps/ip/monitor_ps_processing_system7_0_0/monitor_ps_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==monitor_ps_processing_system7_0_0 || ORIG_REF_NAME==monitor_ps_processing_system7_0_0} -quiet] -quiet

# XDC: bd/monitor_ps/monitor_ps_ooc.xdc
